name: wrf_python_assimilation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - setuptools
  - wheel
  - numpy
  - scipy
  - netcdf4
  - xarray
  - wrf-python
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - jupyter
  - ipykernel
  - compilers
  - fortran-compiler
  - threadpoolctl
  - pip
  - pip:
      - snakeviz
      - line_profiler
      - scalene