paths:
  prepared: /home/jorge.gacitua/datosdemerzel/wrf_python_Assimilation/data/ensemble_cross_sections.npz
  outdir:   /home/jorge.gacitua/datosdemerzel/wrf_python_Assimilation/data/runs/single_obs

state:
  truth_member: 22
  var_idx: {qg: 0, qr: 1, qs: 2, T: 3, P: 4, u: 5, v: 6, w: 7}

obs:
  kind: SINGLE
  loc: {x: 30, y: 0, z: 18}
  sigma_dbz: 5.0

da:
  use_fortran_letkf: true
  ntemp: [1]
  alpha: [2]
  loc_scales: [5,5,5]

experiment_tag: single_obs_baseline
